
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ConsoleLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <nav className='px-8 py-5 bg-[#0d1947]'>Nav</nav>
        {children}
    </>
  )
}
